// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: max_profit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfitClient is the client API for Profit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfitClient interface {
	CalculateMaxProfit(ctx context.Context, in *Profits, opts ...grpc.CallOption) (*MaxProfit, error)
}

type profitClient struct {
	cc grpc.ClientConnInterface
}

func NewProfitClient(cc grpc.ClientConnInterface) ProfitClient {
	return &profitClient{cc}
}

func (c *profitClient) CalculateMaxProfit(ctx context.Context, in *Profits, opts ...grpc.CallOption) (*MaxProfit, error) {
	out := new(MaxProfit)
	err := c.cc.Invoke(ctx, "/Profit/CalculateMaxProfit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfitServer is the server API for Profit service.
// All implementations must embed UnimplementedProfitServer
// for forward compatibility
type ProfitServer interface {
	CalculateMaxProfit(context.Context, *Profits) (*MaxProfit, error)
	mustEmbedUnimplementedProfitServer()
}

// UnimplementedProfitServer must be embedded to have forward compatible implementations.
type UnimplementedProfitServer struct {
}

func (UnimplementedProfitServer) CalculateMaxProfit(context.Context, *Profits) (*MaxProfit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateMaxProfit not implemented")
}
func (UnimplementedProfitServer) mustEmbedUnimplementedProfitServer() {}

// UnsafeProfitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfitServer will
// result in compilation errors.
type UnsafeProfitServer interface {
	mustEmbedUnimplementedProfitServer()
}

func RegisterProfitServer(s grpc.ServiceRegistrar, srv ProfitServer) {
	s.RegisterService(&Profit_ServiceDesc, srv)
}

func _Profit_CalculateMaxProfit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profits)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfitServer).CalculateMaxProfit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profit/CalculateMaxProfit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfitServer).CalculateMaxProfit(ctx, req.(*Profits))
	}
	return interceptor(ctx, in, info, handler)
}

// Profit_ServiceDesc is the grpc.ServiceDesc for Profit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Profit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Profit",
	HandlerType: (*ProfitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateMaxProfit",
			Handler:    _Profit_CalculateMaxProfit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "max_profit.proto",
}
